spring:
  datasource: #数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_business?characterEncoding=utf8&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true
  thymeleaf:
    mode: HTML5
#  servlet:
#    multipart:
#      max-file-size: 20MB
#      max-request-size: 20MB
mybatis:
  mapper-locations: classpath*:com/neuedu/mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml

business:
  host: http://www.yj.tyut.com/

alipay:
  appid: 2016101500694110
  pid: 2088102179721770
  target_id: ""
  rsa2_private: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyuxKsrAU8XGdqz48Z7cp/KN7ci/lUSfZl+IVsAl8aTCOksEuawkpYxL641DPU0aP4G0BZXX4bkyfTepdc8ArHuFO9PjLcpLT9zO5gRkobP1f1TDxw0Fnm1uwwTa0tlYpOQv2opGXtKRZkCo97SfYS+3k8XvG1/CatOYkYhCEerrKSh7wTnS35ra8CNTjkGyxW7IpCbDWSZMfsAjw0hkI/VhSl+IIN4MW4autDm3Hp6eMUwdhaM0O77UC/PVU3nkCf7uuYs2h3q9+k+UgshvbGNqrC3N6p3WPdGvJRb4PgM/xZ7AyDHe5G6Sryy+r1Q9lN2F69wor/xjXggTubiagJAgMBAAECggEBAIbLE3BqY6B8R/qEAvaZIcj49+r5Hdb12QBah7VHrJXWqmMAGmTi9tMvvm8CivyMBs+NLeC34+3D85tIr3MGDftGBtGIYS+KgH2Q2o59NFKMWTfEgSjL2aGAoaxkSKFCUIZpe4h+Q+iyvhJA7KkcxJrYUTy4li6btkeaRszYiWnrLV5PuGjdXZtu/Kt2fewUPvBpfNp6CKk4cV8HNkdy+ISkGZcAc+nII4UsoKrFE28npQL08KePhucdUtdkk6HxcD/mL+Ojkfx0szjtMCDMEf6DLE8LhUTpaTOpjEt2E5NfRBBvO1vHGQIbQL0VetO6/maxRy05w413wQgHtDMbByECgYEA9QIo+S6+m+ccYCnOsnNDfpmCrTqB8RwZuB+zxrBA7N3G7V1F13ru6GZOdr26cy0PyzOJROmrEpbkgfJG8ECLJNb1rFHw3SE+k3iTZ7qfxPK5kn45qE59ROiHRdQVb9EtLoe/+IYBRBOTv1c6INTSebbMBpTMKt9ImQWnpEkKHK0CgYEAur+8YamDk00VAsG4AvkHxRXjCRZsYUOEt2XVQL6y86g0LiLItziVai9V4sas3jBT3I0WCpMugIWRWT+Y6QHyKooiV5RPQwWXvV4Ggc5QYqeyCPTdSGZiK+C0XeQsLtbgeplWIEJBYhX5osxb3zDE+sSuUS+TrpmHI+0L+ceUKE0CgYBaql33ODEZCEEb5Ny0dKr5Yl1VNV14l+l8lV61m+uqu7cth2KdBsT6A0Ht9u/UR0yc6YlWkxHXYzdUTw+pQHk9PL7U8c2sRu0dLXV+4TTWcOvzJfq4KbN5mILWeFEme8W4fkuv8Abv5j66g9Di7V6l49tEZDPZeZ8n4UvUI6M2UQKBgFNEDFWrRGxYMScSgt5odQtuL9WsdtSDS1iOgiAlJxs3A1US01XGV/CJfIzpssg62hl7mrlKWLCbXWxiy+YQpQ5MmvVbvl+OzdJ0awhTmknypZISw9t1Mw6HWUSH6R9VVa+0UM9/WzHFxJHO9qO0Vg/NxD+UrA9sivH8zpsnXqr9AoGASeL8RrDX+BoLlCHHuiK8GjSzGG1w8J8Xp3jyTO722bdyOz+V6CeOvlfdVhvHDFAWEf2rYPE5TtsSXxoe45kSaI4cFjBzSt2v+LRrX4fR7ariw12tRmDbOC1hbLapSwgXvCCXtiHK+NHYDH32oD2hyObby/1ptGwGF6aEypqvJTA=
  notify_url: http://qtm4v4.natappfree.cc/portal/pay/callback.do
  publickey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxBYHeWYZWnnn0OTlMpWTIIX/iSvaO8iN/VtcGYKdAtbv4G+b2BqxT5J9D/dNSjYJtJmQGLPfpcBRHKwL/lQxI68XNfoE/zKXltSXJ0chWu36oYwHafWnK61Q7b8nnN2QBs81veoCW6YJu1jP/xDcNW3eUIRYlMHQ/2eWEsp7qizugQqNS+ZytH6N02TPfKcbAui11cr7ZC1iDDa0CX9o022M6MvhoREew+4acEgdg0y9kJSSe00pyYM4YaTIXvE/PI1PxXXwmijbZMztVNCxdgUkYXY0j0RSs1zNEL13O5rMGHrhQsi/LGVoPm/g8HUfT8ysVTypkhf8bVaoHey3xwIDAQAB
